name: React App CI/CD to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: test-kumar-makala
  GKE_CLUSTER: react-cluster
  GKE_ZONE: us-central1-c
  IMAGE: us-central1-docker.pkg.dev/test-kumar-makala/react-repo/frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Set up gcloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Step 4: Configure Docker for Artifact Registry
      - name: Configure Docker authentication
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Step 5: Install dependencies and build React app
      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # Step 6: Build and push Docker image to Artifact Registry
      - name: Build Docker image
        run: docker build -t $IMAGE:$GITHUB_SHA .

      - name: Push Docker image
        run: docker push $IMAGE:$GITHUB_SHA

      # Step 7: Get GKE credentials
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      # Step 8: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/react-frontend-deployment react-frontend=$IMAGE:$GITHUB_SHA
          kubectl rollout status deployment/react-frontend-deployment
